-- AlterEnum: Add new values to GoogleAccountStatus
ALTER TYPE "GoogleAccountStatus" ADD VALUE IF NOT EXISTS 'REAUTH_REQUIRED';
ALTER TYPE "GoogleAccountStatus" ADD VALUE IF NOT EXISTS 'ERROR';
ALTER TYPE "GoogleAccountStatus" ADD VALUE IF NOT EXISTS 'CONNECTING';

-- AlterEnum: Add new values to ActivityAction
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'GOOGLE_ACCOUNT_RECONNECTED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'GOOGLE_ACCOUNT_REAUTH_REQUIRED';
ALTER TYPE "ActivityAction" ADD VALUE IF NOT EXISTS 'GOOGLE_ACCOUNT_REFRESH_FAILED';
